### ISSUE TITLE
Icon Size - Keep original size or let enter the size

### ISSUE THREAD

**Issue by MajorTomDE** [Latgardi/darwinmenu#1]
Hello,

thanks for this great plasmoid ;-)

I have one little suggestion: Currently the icon is fitted to panel hight. This is not optimal:

![Screenshot_20240522_212403](https://github.com/Latgardi/darwinmenu/assets/76742790/0c621f71-f467-4c34-9352-f8a37cba6d32)

Left: Darwin Menu
Right: Plasma Launcher

So it would be great to keep the original icon size or the add an function for entering the height.

Thank you
Tom

**Comment by Latgardi** [comment]
Hello!
> add an function for entering the height

I think, that this is more optimal solution. And I also think, that relative size will be better. Something like entering size in percent (relative to root element) with max size at 90% (for padding).

**Comment by MajorTomDE** [comment]
Your suggestion is also OK. The main thing is a way to adjust the size :-)
Thank you

**Comment by Latgardi** [comment]
Both methods added in last update.
