### ISSUE TITLE
Not possible to add more than one custom command

### ISSUE THREAD

**Issue by MajorTomDE** [Latgardi/darwinmenu#4]
Hey,

I have the issue that I'm not able to add more than one custom command.

For Example
I add the custom command "konsole", click OK, works fine
Then I add a further custom command "dolphin", click OK but see "konsole" doubled within the menu.
When I go back to the settings > custom command I see here also "konsole" doubled.

**Comment by Latgardi** [comment]
Hello! It will be fixed in next version.

**Comment by MajorTomDE** [comment]
Thank you 🙏🏻

**Comment by Kerrnel** [comment]
Don't think this was ever fixed, why close it?
